FROM osrf/ros:noetic-desktop-full

RUN apt-get update && apt-get install -y \
	vim \
	wget \
	unzip \
	git \
	build-essential

RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    python3-venv \
    can-utils \
    sharutils \
    iproute2 \
    iputils-ping

RUN apt install -y libmuparser-dev

########## ROS setup ##########
RUN mkdir -p /home/ros_catkin_ws/src && \
	cd /home/ros_catkin_ws/src && \
	/bin/bash -c "source /opt/ros/noetic/setup.bash; catkin_init_workspace" && \
	cd /home/ros_catkin_ws && \
	/bin/bash -c "source /opt/ros/noetic/setup.bash; catkin_make" && \
	echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc && \
	echo "source /home/ros_catkin_ws/devel/setup.bash" >> ~/.bashrc && \
	echo "export ROS_PACKAGE_PATH=\${ROS_PACKAGE_PATH}:/home/ros_catkin_ws" >> ~/.bashrc && \
	echo "export ROS_WORKSPACE=/home/ros_catkin_ws" >> ~/.bashrc
## cmk
RUN echo "function cmk(){\n	lastpwd=\$OLDPWD \n	cpath=\$(pwd) \n cd /home/ros_catkin_ws \n catkin_make \$@ \n cd \$cpath \n	OLDPWD=\$lastpwd \n}" >> ~/.bashrc
########## dnn_attitude_estimation ##########
##### NO cache #####
ARG CACHEBUST=1

RUN cd /home/ros_catkin_ws/src && \
    git clone https://github.com/Hibiki1020/dji_rs3pro_ros_controller.git --recursive && \
    cd /home/ros_catkin_ws && \
    /bin/bash -c "source /opt/ros/noetic/setup.bash; catkin_make; source devel/setup.bash"

WORKDIR /home/ros_catkin_ws/